# Generated by Django 3.0 on 2021-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=300)),
                ('news_detail', models.TextField()),
                ('news_photo', models.ImageField(default='', upload_to='photo')),
                ('news_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
